<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RunSettingsFilePath>$(MSBuildProjectDirectory)\.runsettings</RunSettingsFilePath>
        <TestingPlatformCommandLineArguments>--settings ./.runsettings</TestingPlatformCommandLineArguments>
        <EnableMSTestRunner>true</EnableMSTestRunner>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Testing" />
        <PackageReference Include="Bit.BlazorES2019" />
        <PackageReference Include="FakeItEasy" />
        <PackageReference Include="Microsoft.Playwright.MSTest.v4" />
        <PackageReference Include="MSTest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Server\Bit.TemplatePlayground.Server.Web\Bit.TemplatePlayground.Server.Web.csproj" />
        <ProjectReference Include="..\Server\Bit.TemplatePlayground.Server.Api\Bit.TemplatePlayground.Server.Api.csproj" />
        <ProjectReference Include="..\Server\Bit.TemplatePlayground.Server.AppHost\Bit.TemplatePlayground.Server.AppHost.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Net.Http.Headers" />
        <Using Include="System.Net.Http.Json" />
        <Using Include="Bit.TemplatePlayground.Shared" />
        <Using Include="Bit.TemplatePlayground.Server.Web" />
        <Using Include="Bit.TemplatePlayground.Shared.Enums" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.AspNetCore.Components" />
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
        <Using Include="Microsoft.Playwright" />
        <Using Include="Microsoft.Playwright.MSTest" />
        <Using Include="FakeItEasy" />
    </ItemGroup>

</Project>
