<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <UserSecretsId>6677C159-204A-4DB6-8787-2CCCEF43F9AC</UserSecretsId>
        <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
        <BitButilScriptScan>TypeReferences</BitButilScriptScan>

        <!-- Publish only the bit-butil.js modules the app uses. -->
        <BitButilTrimScripts>true</BitButilTrimScripts>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Environment)' != 'Development' And '$(SelfContained)' == 'true'">
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PublishReadyToRunComposite>true</PublishReadyToRunComposite>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Bit.TemplatePlayground.Client.Core.Infrastructure.Services" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Bit.BlazorES2019" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Shared\Bit.TemplatePlayground.Server.Shared.csproj" />
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Api\Bit.TemplatePlayground.Server.Api.csproj" />
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Web\Bit.TemplatePlayground.Client.Web.csproj" />
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Core\Bit.TemplatePlayground.Client.Core.csproj" />
        <!-- By referencing Client.Core in Server.Web project, you can build the Client.Web project just once and then unload it during development with Blazor Server, which significantly speeds up build times. -->
    </ItemGroup>

    <ItemGroup Condition="'$(Environment)' != 'Development'">
        <Compile Remove="Infrastructure\Services\FileWatcherService.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\Bit.TemplatePlayground.Server.Api\appsettings*.json">
            <Link>%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="..\Bit.TemplatePlayground.Server.Api\AppCertificate*">
            <Link>%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <DependentUpon>AppCertificate.md</DependentUpon>
        </None>
    </ItemGroup>

    <!--
    https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container
    https://learn.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties
    -->
    <PropertyGroup>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <EnableSdkContainerDebugging Condition="'$(Environment)' == 'Development'">True</EnableSdkContainerDebugging>
    </PropertyGroup>

</Project>
