<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <UserSecretsId>BDAE9668-FD5B-4590-BC3F-81234347FCCF</UserSecretsId>
        <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="NWebsec.AspNetCore.Middleware" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Api\Bit.TemplatePlayground.Server.Api.csproj" />
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Web\Bit.TemplatePlayground.Client.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Bit.TemplatePlayground.Shared.Enums" />
    </ItemGroup>

    <!--
    https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container
    https://learn.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties
    -->
    <PropertyGroup>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <EnableSdkContainerDebugging Condition="'$(Configuration)' == 'Debug'">True</EnableSdkContainerDebugging>
    </PropertyGroup>

</Project>
