<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <IsAspireHost>true</IsAspireHost>
        <EntryPointAccessibility>public</EntryPointAccessibility>
        <UserSecretsId>5EF6E154-8968-4DDC-96A9-123768AF52DD</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <Content Include=".config\dotnet-tools.json" />
        <PackageReference Include="Aspire.Hosting.AppHost" />
        <PackageReference Include="Aspire.Hosting.DevTunnels" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Web\Bit.TemplatePlayground.Client.Web.csproj" />
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Windows\Bit.TemplatePlayground.Client.Windows.csproj" />
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Web\Bit.TemplatePlayground.Server.Web.csproj" />
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Shared\Bit.TemplatePlayground.Server.Shared.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
