<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <IsAspireHost>true</IsAspireHost>
        <EntryPointAccessibility>public</EntryPointAccessibility>
        <UserSecretsId>DF5E168C-E8B4-4240-9CB5-A2336C02B23E</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" />
        <PackageReference Include="Aspire.Hosting.DevTunnels" />
        <PackageReference Include="Aspire.Hosting.Keycloak" />
        <PackageReference Include="Aspire.Hosting.Maui" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Web\Bit.TemplatePlayground.Client.Web.csproj" />
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Windows\Bit.TemplatePlayground.Client.Windows.csproj" />
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Web\Bit.TemplatePlayground.Server.Web.csproj" />
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Shared\Bit.TemplatePlayground.Server.Shared.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
