<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <IsAspireHost>true</IsAspireHost>
        <EntryPointAccessibility>public</EntryPointAccessibility>
        <UserSecretsId>6677C159-204A-4DB6-8787-2CCCEF43F9AC</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Shirubasoft.Aspire.CloudflareTunnels" />
        <PackageReference Include="Aspire.Hosting.Keycloak" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Web\Bit.TemplatePlayground.Client.Web.csproj" />
        <ProjectReference Include="..\..\Client\Bit.TemplatePlayground.Client.Windows\Bit.TemplatePlayground.Client.Windows.csproj" />
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Web\Bit.TemplatePlayground.Server.Web.csproj" />
        <ProjectReference Include="..\Bit.TemplatePlayground.Server.Shared\Bit.TemplatePlayground.Server.Shared.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
